DROP TABLE `RefReport`.`TJ_INDICATOR_TO_REPORT`;
ALTER TABLE `RefReport`.`T_GROUP_REPORT_CONFIG` DROP FOREIGN KEY FK_4ppd6gfxc92r3gkrd3lywnd5l;
ALTER TABLE `RefReport`.`T_GROUP_REPORT_CONFIG` DROP COLUMN `FILTER_FK`;
DROP TABLE `RefReport`.`T_FILTER`;
DELETE FROM `RefReport`.`T_GROUP_REPORT_CONFIG` WHERE `REPORTING_GROUP_FK` IS NULL;
ALTER TABLE `RefReport`.`T_GROUP_REPORT_CONFIG` MODIFY COLUMN `REPORTING_GROUP_FK` BIGINT(20) NOT NULL;
UPDATE T_REPORT_OUTPUT SET TYPE='DBH2' WHERE TYPE = 'DB';
UPDATE T_REPORT_CONFIG SET TYPE='DBH2' WHERE TYPE = 'DB';
